<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.0.1</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.rodriguezblanco</groupId>
	<artifactId>priceservice</artifactId>
	<version>1.0.0</version>
	<name>Price Service</name>
	<description>Service to search for product prices</description>
	<url/>
	<licenses>
		<license/>
	</licenses>
	<developers>
		<developer/>
	</developers>
	<scm>
		<connection/>
		<developerConnection/>
		<tag/>
		<url/>
	</scm>
	<properties>
		<java.version>25</java.version>
		<cucumber.version>7.33.0</cucumber.version>
		<test.tags/>
		<cucumber.filter.tags/>
		<cucumber.ansi-colors>true</cucumber.ansi-colors>
	</properties>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>io.cucumber</groupId>
				<artifactId>cucumber-bom</artifactId>
				<version>${cucumber.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webmvc</artifactId>
		</dependency>

		<!-- OpenApi UI-->
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>3.0.0</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>

		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-spring</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit-platform-engine</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.junit.platform</groupId>
			<artifactId>junit-platform-suite</artifactId>
			<scope>test</scope>
		</dependency>


		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webmvc-test</artifactId>
			<scope>test</scope>
		</dependency>

		<!-- Source: https://mvnrepository.com/artifact/me.fabriciorby/maven-surefire-junit5-tree-reporter -->
		<dependency>
			<groupId>me.fabriciorby</groupId>
			<artifactId>maven-surefire-junit5-tree-reporter</artifactId>
			<version>1.5.1</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.5.3</version>
				<dependencies>
					<dependency>
						<groupId>me.fabriciorby</groupId>
						<artifactId>maven-surefire-junit5-tree-reporter</artifactId>
						<version>1.5.1</version>
					</dependency>
				</dependencies>
				<configuration>
					<useModulePath>false</useModulePath>
					<useFile>false</useFile>
					<printSummary>true</printSummary>
					<reportFormat>plain</reportFormat>
					<trimStackTrace>true</trimStackTrace>
					<statelessTestsetInfoReporter
							implementation="org.apache.maven.plugin.surefire.extensions.junit5.JUnit5StatelessTestsetInfoTreeReporter">
					</statelessTestsetInfoReporter>
					<argLine>
						-javaagent:${settings.localRepository}/org/mockito/mockito-core/${mockito.version}/mockito-core-${mockito.version}.jar
						-Xshare:off
					</argLine>
				</configuration>
				<executions>
					<execution>
						<id>unit</id>
						<configuration>
							<includes>
								<include>**/UnitSuite.java</include>
							</includes>
							<consoleOutputReporter>
								<disable>true</disable>
							</consoleOutputReporter>
						</configuration>
					</execution>
					<execution>
						<id>integration</id>
						<configuration>
							<includes>
								<include>**/IntegrationSuite.java</include>
							</includes>
							<consoleOutputReporter>
								<disable>true</disable>
							</consoleOutputReporter>
						</configuration>
					</execution>
					<execution>
						<id>acceptance</id>
						<configuration>
							<includes>
								<include>**/AcceptanceSuite.java</include>
							</includes>
							<consoleOutputReporter>
								<disable>false</disable>
							</consoleOutputReporter>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<!-- Integration + Acceptance tests -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>3.5.3</version>
				<configuration>
					<useFile>false</useFile>
					<printSummary>true</printSummary>
					<reportFormat>plain</reportFormat>
					<trimStackTrace>true</trimStackTrace>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>
	<profiles>

		<!-- Unit tests -->
		<profile>
			<id>unit</id>
			<properties>
				<test>**/UnitSuite.java</test>
			</properties>
		</profile>

		<!-- Integration tests -->
		<profile>
			<id>integration</id>
			<properties>
				<test>**/IntegrationSuite.java</test>
			</properties>
		</profile>

		<!-- Acceptance -->
		<profile>
			<id>acceptance</id>
			<properties>
				<test>**/AcceptanceSuite.java</test>
			</properties>
		</profile>

	</profiles>

</project>
