spring.application.name=priceservice
# Springdoc OpenApi configuration
springdoc.api-docs.enabled=false
springdoc.swagger-ui.url=/doc/api/openapi/openapi.yaml
# H2 database
spring.datasource.url=jdbc:h2:mem:pricesdb
spring.datasource.driver-class-name=org.h2.Driver
