spring.application.name=@project.name@
application.name=@project.name@
application.description=@project.description@
application.version=@project.version@
# Springdoc OpenApi configuration
#springdoc.api-docs.enabled=false
#springdoc.swagger-ui.url=/doc/api/openapi/openapi.yaml
springdoc.api-docs.path=/docs
# H2 database
spring.datasource.url=jdbc:h2:mem:pricesdb
spring.datasource.driver-class-name=org.h2.Driver
